# Generated by Django 6.0.1 on 2026-01-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issue_number', models.IntegerField()),
                ('release_date', models.DateField()),
                ('coverType', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
            ],
        ),
    ]
