# Generated by Django 6.0.1 on 2026-01-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='condition',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='comic',
            name='status',
            field=models.CharField(choices=[('owned', 'Owned'), ('wanted', 'Wanted')], default='owned', max_length=10),
        ),
        migrations.AlterField(
            model_name='comic',
            name='artist',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comic',
            name='publisher',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comic',
            name='writer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
