# Generated by Django 6.0.1 on 2026-01-10 23:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_comic_condition_comic_status_alter_comic_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
